import type { Metadata } from 'next';
import Link from 'next/link';
import { PolicyPage, PolicySection } from '../../components/PolicyPage';

export const metadata: Metadata = { title: 'AppToolkitLab Privacy Policy', description: 'How AppToolkitLab collects, uses, retains, protects, and discloses account, conversion, usage, order, and support information.' };

export default function PrivacyPage() {
  return <PolicyPage eyebrow="Privacy policy" title="Your data should be processed for a clear reason—and no longer than needed." description="This notice describes the intended information practices for AppToolkitLab public tools, accounts, conversions, subscriptions, software purchases, and support." currentPath="/privacy">
    <PolicySection id="scope" title="1. Scope and responsible operator"><p>This policy applies to AppToolkitLab websites, public tools, customer workspaces, APIs, software marketplace, and related support. AppToolkitLab is a Gonexel product. Before production launch, the responsible legal entity, registered address, privacy contact, and representative details must be inserted. A customer may also be responsible for personal data contained in files it uploads.</p></PolicySection>
    <PolicySection id="collect" title="2. Information we collect"><h3>Information you provide</h3><ul><li>Account and organization details such as name, email, authentication data, team membership, and preferences.</li><li>Files, HTML, Markdown, images, URLs, job settings, and instructions submitted for processing.</li><li>Order, billing-contact, tax, license, activation, and support information. Payment providers process full card or bank credentials; AppToolkitLab should retain only necessary references and status data.</li></ul><h3>Information collected during use</h3><ul><li>Job status, input/output formats, size, processing duration, error details, quota consumption, API activity, and download events.</li><li>Device, browser, approximate location, security, and server-log information needed to operate and protect the service.</li><li>For anonymous quotas, a signed first-party cookie and a keyed hash derived from network information. The design does not require storing the raw IP address in the quota record, though infrastructure logs may temporarily contain it.</li></ul></PolicySection>
    <PolicySection id="use" title="3. Why we use information"><ul><li>Provide requested conversions, webpage captures, OCR, exports, downloads, licenses, and account features.</li><li>Authenticate users, reserve and settle quotas, process orders, issue invoices, and provide support.</li><li>Protect the service, investigate abuse, prevent fraud, debug failures, and maintain audit records.</li><li>Improve reliability and usability using aggregated or appropriately de-identified operational information.</li><li>Meet legal, tax, accounting, security, and regulatory obligations.</li></ul><p>Where required, processing should rely on an appropriate basis such as performance of a contract, consent, legitimate interests assessed against user rights, or compliance with law.</p></PolicySection>
    <PolicySection id="sharing" title="4. When information is disclosed"><p>Information may be disclosed to Gonexel and configured hosting, storage, conversion, analytics, communications, customer-support, security, payment, and professional-service providers only as needed for their role. Stripe may support international payments and Razorpay may support INR payments when enabled. Information may also be disclosed when legally required, to protect rights and safety, or as part of a business transaction subject to appropriate safeguards.</p><p>AppToolkitLab&apos;s current policy is not to sell personal information or share it for cross-context behavioral advertising.</p></PolicySection>
    <PolicySection id="retention" title="5. File and record retention"><p>Configured targets are up to 24 hours for anonymous or Free file processing, 30 days for Pro, and 90 days for Business. Actual deletion can happen sooner after a user request, failed job, security event, or operational cleanup. Account data is kept while the account is active and then for a reasonable closure period.</p><p>Order, invoice, tax, fraud-prevention, license, security, dispute, and audit records may be retained longer where needed for law or legitimate business protection. Backups are isolated and expire on a separate schedule; immediate removal from every backup may not be technically possible.</p></PolicySection>
    <PolicySection id="security" title="6. Security"><p>The intended safeguards include encrypted transport, password hashing, HttpOnly refresh cookies, short-lived access tokens, authorization checks, restricted object storage, isolated workers, URL safety checks, signed downloads, webhook signature verification, rate limits, secrets management, and audit logging. No internet service is risk-free, so users should avoid uploading data that is not necessary for the task.</p></PolicySection>
    <PolicySection id="transfers" title="7. International processing"><p>Providers may process information outside the user&apos;s state or country. Before launch, AppToolkitLab must document hosting regions and use a lawful transfer mechanism where required, such as contractual safeguards and transfer-risk review.</p></PolicySection>
    <PolicySection id="rights" title="8. Your choices and rights"><p>Depending on applicable law, a person may request access, correction, deletion, portability, restriction, objection, withdrawal of consent, or review of certain automated decisions. California residents may also have rights to know, correct, delete, opt out of sale or sharing, and limit certain uses of sensitive information. AppToolkitLab does not currently sell or share data for cross-context advertising.</p><p>Requests can be started through <Link href="/contact">the contact page</Link>. Identity or authority may need to be verified. Some information cannot be deleted when retention is legally required.</p></PolicySection>
    <PolicySection id="children" title="9. Children"><p>AppToolkitLab is intended for business and general productivity use and is not directed to children. The final launch terms must set an age threshold appropriate to the operator&apos;s markets and obtain legally required parental authorization where applicable.</p></PolicySection>
    <PolicySection id="changes" title="10. Changes and contact"><p>Material changes will be dated and communicated where required. Questions or complaints can be submitted through <Link href="/contact">Contact support</Link>. Read <Link href="/data-policy">Data Protection &amp; Applicable Law</Link> for jurisdiction-specific context.</p></PolicySection>
  </PolicyPage>;
}
